name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create book folder
      run: mkdir book
    - uses: actions/checkout@v2
    - name: install mdbook
      run: cargo install mdbook
    - name: build mdbook
      run: mdbook build
