name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install mdbook
      run: |
        mkdir book
        (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
        cargo install-update -a
    - name: build mdbook
      run: mdbook build
