language: rust
sudo: false

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


cache:
  - cargo

rust:
  - stable

before_script:
  - mkdir book
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - cargo install-update -a

script:
  - mdbook build ./book

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build mdbook
      run: mdbook build ./book
