name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update resources
      run: mkdir book
      with:
        file-path: /book
        commit-msg: Update resources
        github-token: ${{ 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 }}
    - uses: actions/checkout@v2
    - name: install mdbook
      run: cargo install mdbook
    - name: build mdbook
      run: mdbook build

